// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#import "TestInfoStore.h"
#include "test_info_store.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TestInfoStore;

namespace djinni_generated {

struct TestInfoStore
{
    using CppType = ::test::hello::TestInfoStore;
    using ObjcType = TestInfoStore*;

    using Boxed = TestInfoStore;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
