// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#include "test_djnni_interface.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TestDjnniInterface;

namespace djinni_generated {

class TestDjnniInterface
{
public:
    using CppType = std::shared_ptr<::test::hello::TestDjnniInterface>;
    using CppOptType = std::shared_ptr<::test::hello::TestDjnniInterface>;
    using ObjcType = TestDjnniInterface*;

    using Boxed = TestDjnniInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

