// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#import "TestDjnniInterface+Private.h"
#import "TestDjnniInterface.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "TestInfoStore+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TestDjnniInterface ()

- (id)initWithCpp:(const std::shared_ptr<::test::hello::TestDjnniInterface>&)cppRef;

@end

@implementation TestDjnniInterface {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::test::hello::TestDjnniInterface>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::test::hello::TestDjnniInterface>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)show:(nonnull TestInfoStore *)testInfo {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->Show(::djinni_generated::TestInfoStore::toCpp(testInfo));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable TestDjnniInterface *)newInstance {
    try {
        auto objcpp_result_ = ::test::hello::TestDjnniInterface::NewInstance();
        return ::djinni_generated::TestDjnniInterface::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}


namespace djinni_generated {

auto TestDjnniInterface::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TestDjnniInterface::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TestDjnniInterface>(cpp);
}

}  // namespace djinni_generated

@end
