// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#import "TestInfoStore+Private.h"
#import "DJIMarshal+Private.h"
#import "SexModeEnum+Private.h"
#include <cassert>

namespace djinni_generated {

auto TestInfoStore::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::String::toCpp(obj.name),
            ::djinni::String::toCpp(obj.project),
            ::djinni::Enum<::test::hello::SexModeEnum, SexModeEnum>::toCpp(obj.sex)};
}

auto TestInfoStore::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TestInfoStore alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                        name:(::djinni::String::fromCpp(cpp.name))
                                     project:(::djinni::String::fromCpp(cpp.project))
                                         sex:(::djinni::Enum<::test::hello::SexModeEnum, SexModeEnum>::fromCpp(cpp.sex))];
}

}  // namespace djinni_generated
