// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#include "test_djnni_interface.h"  // my header
#include "test_info_store.h"

namespace test { namespace hello {

int32_t constexpr TestDjnniInterface::VERSION;

} }  // namespace test::hello
