// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include "djinni_support.hpp"
#include "sex_mode_enum.h"

namespace djinni_generated {

class JNISexModeEnum final : ::djinni::JniEnum {
public:
    using CppType = ::test::hello::SexModeEnum;
    using JniType = jobject;

    using Boxed = JNISexModeEnum;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<JNISexModeEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<JNISexModeEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    JNISexModeEnum() : JniEnum("com/zhoumohan/djinni/gen/SexModeEnum") {}
    friend ::djinni::JniClass<JNISexModeEnum>;
};

}  // namespace djinni_generated
