// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#import "SexModeEnum.h"
#import <Foundation/Foundation.h>

@interface TestInfoStore : NSObject
- (nonnull instancetype)initWithId:(int32_t)id
                              name:(nonnull NSString *)name
                           project:(nonnull NSString *)project
                               sex:(SexModeEnum)sex;
+ (nonnull instancetype)testInfoStoreWithId:(int32_t)id
                                       name:(nonnull NSString *)name
                                    project:(nonnull NSString *)project
                                        sex:(SexModeEnum)sex;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * project;

@property (nonatomic, readonly) SexModeEnum sex;

@end
