// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// test_hello_Bridging_Header.h
// test_hello_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for testhelloBridgingHeader.
FOUNDATION_EXPORT double testhelloBridgingHeaderVersionNumber;

//! Project version string for testhelloBridgingHeader.
FOUNDATION_EXPORT const unsigned char testhelloBridgingHeaderVersionString[];

#import "SexModeEnum.h"
#import "TestInfoStore.h"
#import "TestDjnniInterface.h"
