// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#import "TestInfoStore.h"
#import <Foundation/Foundation.h>
@class TestDjnniInterface;

extern int32_t const TestDjnniInterfaceVersion;

@interface TestDjnniInterface : NSObject

- (nonnull NSString *)show:(nonnull TestInfoStore *)testInfo;

+ (nullable TestDjnniInterface *)newInstance;

@end
